#!/usr/bin/env python3
"""
generate_data.py - Synthetic MongoDB dataset generator for a campus
social / activity-matching app (HackCMU project).

Generates two collections:
  - users:      people with a home location, interests, bio, availability
  - activities: user-posted "let's do X" activities with ground-truth
                 keyword labels and a location near their creator

Design goals:
  - Zero external dependencies (Python stdlib only: random, json, math,
    argparse, datetime, pathlib, uuid, collections).
  - Locations cluster around 5 weighted Pittsburgh hotspots using
    Gaussian jitter (random.gauss), NOT uniform noise, so a heatmap
    over this data shows realistic hot/cold zones.
  - A fixed vocabulary of ~30 interest/activity tags is shared between
    users.interests and activities.keywords so overlap is meaningful
    and testable (e.g. for matching / recommendation algorithms).
  - activities.raw_text is generated by filling varied sentence
    templates with the activity's keywords, so it reads like a real
    user post -- useful for testing an LLM-based keyword extractor
    against the known-good activities.keywords ground truth.

Usage:
    python3 generate_data.py --users 1000 --activities 400
    python3 generate_data.py --users 5000 --activities 2000 --seed 42

Output (written to ./output/ relative to this script):
    users.json           JSONL, one user doc per line (mongoimport-ready)
    activities.json      JSONL, one activity doc per line (mongoimport-ready)
    users.pretty.json     indented JSON array, for humans
    activities.pretty.json indented JSON array, for humans
"""

import argparse
import json
import random
import uuid
from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path

# --------------------------------------------------------------------------
# Fixed vocabulary: ~30 campus-relevant interest / activity tags.
# Shared by users.interests and activities.keywords so overlap between
# the two collections is meaningful (not comparing arbitrary free text).
# --------------------------------------------------------------------------
INTEREST_VOCAB = [
    "hiking",
    "boba",
    "coffee chats",
    "board games",
    "rock climbing",
    "career advice",
    "workout",
    "studying",
    "coding",
    "photography",
    "basketball",
    "soccer",
    "movies",
    "live music",
    "cooking",
    "baking",
    "yoga",
    "running",
    "cycling",
    "video games",
    "chess",
    "startups",
    "research",
    "art",
    "painting",
    "volunteering",
    "book club",
    "trivia night",
    "karaoke",
    "thrifting",
    "networking",
    "meditation",
]

# --------------------------------------------------------------------------
# Geographic hotspots: (name, lat, lng, weight)
# Approximate real coordinates for Pittsburgh neighborhoods relevant to a
# CMU-centric campus social app. Weights control how many users/activities
# cluster around each spot.
# --------------------------------------------------------------------------
HOTSPOTS = [
    {"name": "CMU Campus", "lat": 40.4443, "lng": -79.9436, "weight": 0.35},
    {"name": "Downtown Pittsburgh", "lat": 40.4406, "lng": -79.9959, "weight": 0.15},
    {"name": "Shadyside", "lat": 40.4520, "lng": -79.9343, "weight": 0.20},
    {"name": "South Side", "lat": 40.4285, "lng": -79.9739, "weight": 0.10},
    {"name": "North Oakland", "lat": 40.4531, "lng": -79.9557, "weight": 0.20},
]

# Standard deviation of Gaussian jitter around a hotspot, in degrees.
# ~0.006 degrees latitude is roughly 650m, giving a plausible walkable
# "neighborhood" spread without spots bleeding into one another.
JITTER_SIGMA_DEG = 0.006

AVAILABILITY_OPTIONS = ["morning", "afternoon", "evening", "night"]
AGE_RANGES = ["18-20", "21-23", "24-26", "27-30"]
ACTIVITY_STATUSES = ["open", "matched", "closed"]
# Weighted so most freshly generated activities are still "open".
ACTIVITY_STATUS_WEIGHTS = [0.65, 0.20, 0.15]
ACTIVITY_DURATIONS_MINUTES = {
    "workout": 60,
    "coding": 90,
    "basketball": 90,
    "coffee chats": 45,
    "walking": 30,
}

# --------------------------------------------------------------------------
# Hand-rolled name lists (no `faker` dependency).
# --------------------------------------------------------------------------
FIRST_NAMES = [
    "Aiden", "Amara", "Ben", "Chloe", "Daniel", "Emma", "Ethan", "Fatima",
    "Grace", "Hassan", "Isabella", "Jack", "Jia", "Kevin", "Layla", "Liam",
    "Maya", "Mia", "Noah", "Olivia", "Priya", "Quinn", "Ravi", "Sofia",
    "Tariq", "Uma", "Victor", "Wei", "Ximena", "Yusuf", "Zara", "Alex",
    "Bella", "Carlos", "Diana", "Elena", "Felix", "Gabriela", "Henry",
    "Ines", "Jamal", "Kira", "Leo", "Mona", "Nina", "Oscar", "Priyanka",
    "Quentin", "Rosa", "Sam", "Tara", "Umar", "Vera", "Will", "Xiao",
    "Yara", "Zach", "Abby", "Brian", "Cindy", "Derek",
]

LAST_NAMES = [
    "Chen", "Patel", "Kim", "Nguyen", "Garcia", "Smith", "Johnson",
    "Williams", "Brown", "Davis", "Rodriguez", "Martinez", "Lee", "Wang",
    "Khan", "Ahmed", "Silva", "Kumar", "Singh", "Zhao", "Wilson", "Moore",
    "Taylor", "Anderson", "Thomas", "Jackson", "White", "Harris", "Clark",
    "Lewis", "Robinson", "Walker", "Young", "Allen", "King", "Wright",
    "Scott", "Torres", "Nelson", "Baker", "Adams", "Nair", "Iyer",
    "Suzuki", "Tanaka", "Kowalski", "Novak", "Fernandez", "Rossi",
    "Muller",
]

# --------------------------------------------------------------------------
# ~18 varied sentence templates for activities.raw_text. Each template has
# 2-4 `{kw}` placeholder slots (kw0, kw1, kw2, kw3) that get filled with
# keywords drawn from the activity's own `keywords` list, so the raw text
# reads naturally while still containing the ground-truth tags.
# --------------------------------------------------------------------------
RAW_TEXT_TEMPLATES = [
    "wanna grab {kw0} and talk about {kw1}?",
    "looking for someone to do {kw0} with this week, anyone down?",
    "hosting a casual {kw0} session, all levels welcome!",
    "need a study buddy for {kw0}, also open to chatting about {kw1}",
    "who's up for {kw0} later? thinking of making it a regular thing",
    "trying to find people into {kw0} and {kw1} near campus",
    "free this weekend for {kw0}? would love some company",
    "starting a small group for {kw0} + {kw1}, msg me if interested",
    "anyone want to hit up {kw0} with me, kind of a {kw1} mood today",
    "looking to swap {kw0} tips over {kw1}, coffee's on me",
    "planning a low-key {kw0} meetup, bring a friend if you want",
    "bored and want to do {kw0}, bonus points if you're also into {kw1}",
    "new to the area and hoping to find a {kw0} crew",
    "taking a break from {kw0} to do some {kw1}, join if you're around",
    "organizing {kw0} for beginners, no experience needed",
    "would love to find a regular {kw0} partner, into {kw1} too",
    "feeling like {kw0} today, anyone want to tag along?",
    "putting together a {kw0} night, thinking {kw1} after if people are down",
    "looking for recommendations and company for {kw0} this {kw1}",
    "trying to get back into {kw0}, would help to have someone doing {kw1} with me",
]

BIO_TEMPLATES = [
    "into {kw0} and {kw1}, always down to meet new people on campus.",
    "grad student who spends too much time on {kw0}, trying to balance it with {kw1}.",
    "here for the {kw0} scene, also love a good {kw1} session.",
    "new to Pittsburgh, excited about {kw0} and looking for {kw1} buddies.",
    "usually found doing {kw0} between classes, {kw1} on weekends.",
    "big fan of {kw0}, still figuring out {kw1} but willing to learn.",
    "trying to meet people who like {kw0} as much as I do.",
    "campus regular, {kw0} enthusiast, occasional {kw1} dabbler.",
    "juggling classes and {kw0}, always looking for {kw1} recommendations.",
    "moved here for school, staying for the {kw0} and {kw1}.",
    "spend most free time on {kw0}, recently got into {kw1}.",
    "low-key obsessed with {kw0}, happy to talk {kw1} anytime.",
]


def weighted_choice(rng: random.Random, items):
    """Pick one item from a list of dicts with a 'weight' key."""
    weights = [it["weight"] for it in items]
    return rng.choices(items, weights=weights, k=1)[0]


def jittered_point(rng: random.Random, hotspot):
    """
    Return a GeoJSON Point near `hotspot`, using Gaussian jitter
    (random.gauss) instead of uniform noise, so density falls off
    naturally from the hotspot center.
    """
    lat = hotspot["lat"] + rng.gauss(0, JITTER_SIGMA_DEG)
    lng = hotspot["lng"] + rng.gauss(0, JITTER_SIGMA_DEG)
    # Clamp to sane bounds (safety net; jitter sigma is small so this
    # essentially never triggers).
    lat = max(-90.0, min(90.0, lat))
    lng = max(-180.0, min(180.0, lng))
    return {"type": "Point", "coordinates": [round(lng, 6), round(lat, 6)]}


def random_name(rng: random.Random):
    return f"{rng.choice(FIRST_NAMES)} {rng.choice(LAST_NAMES)}"


def name_to_email(name: str, dedupe_suffix: int | None = None):
    local = name.lower().replace(" ", ".")
    if dedupe_suffix is not None:
        local = f"{local}{dedupe_suffix}"
    return f"{local}@andrew.cmu.edu"


def random_created_at(rng: random.Random, now: datetime):
    """ISO 8601 timestamp spread over roughly the last 30 days."""
    seconds_back = rng.uniform(0, 30 * 24 * 3600)
    ts = now - timedelta(seconds=seconds_back)
    return ts.isoformat().replace("+00:00", "Z")


def make_bio(rng: random.Random, interests):
    template = rng.choice(BIO_TEMPLATES)
    kw0 = rng.choice(interests)
    kw1 = rng.choice(interests)
    return template.format(kw0=kw0, kw1=kw1)


def make_raw_text(rng: random.Random, keywords):
    template = rng.choice(RAW_TEXT_TEMPLATES)
    # Figure out how many distinct {kwN} slots this template needs.
    needed = sum(1 for tag in ("{kw0}", "{kw1}", "{kw2}", "{kw3}") if tag in template)
    needed = max(needed, 1)
    pool = list(keywords)
    while len(pool) < needed:
        pool.append(rng.choice(keywords))
    chosen = rng.sample(pool, needed) if len(pool) >= needed else pool
    slots = {f"kw{i}": chosen[i] for i in range(needed)}
    # Fill any unused slot names defensively (shouldn't be needed given
    # `needed` computation above, but keeps .format() from KeyError-ing
    # if a template is edited later without updating slot counts).
    for i in range(4):
        slots.setdefault(f"kw{i}", rng.choice(keywords))
    return template.format(**slots)


def generate_users(rng: random.Random, count: int, now: datetime):
    users = []
    seen_emails = Counter()
    for _ in range(count):
        name = random_name(rng)
        base_email = name_to_email(name)
        seen_emails[base_email] += 1
        email = base_email if seen_emails[base_email] == 1 else name_to_email(
            name, seen_emails[base_email]
        )

        hotspot = weighted_choice(rng, HOTSPOTS)
        location = jittered_point(rng, hotspot)

        n_interests = rng.randint(3, 6)
        interests = rng.sample(INTEREST_VOCAB, n_interests)

        user = {
            "_id": str(uuid.uuid4()),
            "name": name,
            "email": email,
            "location": location,
            "interests": interests,
            "bio": make_bio(rng, interests),
            "availability": rng.choice(AVAILABILITY_OPTIONS),
            "age_range": rng.choice(AGE_RANGES),
            "created_at": random_created_at(rng, now),
            "_hotspot": hotspot["name"],  # internal, stripped before output
        }
        users.append(user)
    return users


def generate_activities(rng: random.Random, count: int, users, now: datetime):
    activities = []
    hotspot_by_name = {h["name"]: h for h in HOTSPOTS}
    for _ in range(count):
        creator = rng.choice(users)
        creator_hotspot = hotspot_by_name[creator["_hotspot"]]

        n_keywords = rng.randint(2, 4)
        keywords = rng.sample(INTEREST_VOCAB, n_keywords)

        # Activity location is near the creator's own location: jitter
        # again around the same hotspot the creator belongs to.
        location = jittered_point(rng, creator_hotspot)
        start = now + timedelta(minutes=rng.randint(0, 24 * 60))
        duration = ACTIVITY_DURATIONS_MINUTES.get(keywords[0], 60)

        activity = {
            "_id": str(uuid.uuid4()),
            "creator_id": creator["_id"],
            "raw_text": make_raw_text(rng, keywords),
            "keywords": keywords,
            "location": location,
            "status": rng.choices(ACTIVITY_STATUSES, weights=ACTIVITY_STATUS_WEIGHTS, k=1)[0],
            "availability": rng.choice(AVAILABILITY_OPTIONS),
            "created_at": random_created_at(rng, now),
            "start_time": start.isoformat().replace("+00:00", "Z"),
            "duration_minutes": duration,
        }
        activities.append(activity)
    return activities


def strip_internal_fields(docs):
    """Return copies of docs with any leading-underscore-prefixed
    scratch keys (except _id) removed, for output."""
    cleaned = []
    for doc in docs:
        cleaned.append({k: v for k, v in doc.items() if k == "_id" or not k.startswith("_")})
    return cleaned


def write_jsonl(path: Path, docs):
    with path.open("w") as f:
        for doc in docs:
            f.write(json.dumps(doc, ensure_ascii=False))
            f.write("\n")


def write_pretty_json(path: Path, docs):
    with path.open("w") as f:
        json.dump(docs, f, ensure_ascii=False, indent=2)
        f.write("\n")


def summarize_hotspot_distribution(users):
    counts = Counter(u["_hotspot"] for u in users)
    total = len(users)
    lines = []
    for h in HOTSPOTS:
        name = h["name"]
        n = counts.get(name, 0)
        pct = (n / total * 100) if total else 0
        lines.append(f"    {name:<22} {n:>6}  ({pct:5.1f}%)")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate synthetic MongoDB dataset for a campus "
        "social / activity-matching app."
    )
    parser.add_argument("--users", type=int, default=1000, help="number of user docs to generate (default: 1000)")
    parser.add_argument("--activities", type=int, default=400, help="number of activity docs to generate (default: 400)")
    parser.add_argument("--seed", type=int, default=None, help="random seed for reproducible output (default: unseeded)")
    parser.add_argument(
        "--out-dir",
        type=str,
        default=None,
        help="output directory (default: ./output next to this script)",
    )
    args = parser.parse_args()

    rng = random.Random(args.seed)
    now = datetime.now(timezone.utc)

    script_dir = Path(__file__).resolve().parent
    out_dir = Path(args.out_dir).resolve() if args.out_dir else script_dir / "output"
    out_dir.mkdir(parents=True, exist_ok=True)

    users = generate_users(rng, args.users, now)
    activities = generate_activities(rng, args.activities, users, now)

    users_out = strip_internal_fields(users)
    activities_out = strip_internal_fields(activities)

    write_jsonl(out_dir / "users.json", users_out)
    write_jsonl(out_dir / "activities.json", activities_out)
    write_pretty_json(out_dir / "users.pretty.json", users_out)
    write_pretty_json(out_dir / "activities.pretty.json", activities_out)

    status_counts = Counter(a["status"] for a in activities_out)

    print("Synthetic data generation complete.")
    print(f"  users:      {len(users_out):>6}  -> {out_dir / 'users.json'}")
    print(f"  activities: {len(activities_out):>6}  -> {out_dir / 'activities.json'}")
    print()
    print("Hotspot distribution (users):")
    print(summarize_hotspot_distribution(users))
    print()
    print("Activity status distribution:")
    for status in ACTIVITY_STATUSES:
        n = status_counts.get(status, 0)
        pct = (n / len(activities_out) * 100) if activities_out else 0
        print(f"    {status:<10} {n:>6}  ({pct:5.1f}%)")
    print()
    print("Output files:")
    for fname in ("users.json", "activities.json", "users.pretty.json", "activities.pretty.json"):
        fpath = out_dir / fname
        size = fpath.stat().st_size
        print(f"    {fpath}  ({size:,} bytes)")


if __name__ == "__main__":
    main()
